name: 📝 작업 이슈
description: 진행할 작업 내용과 상세 TODO를 작성해주세요.
title: "[BE] "
labels: ["task"]
body:
  - type: textarea
    id: work-content
    attributes:
      label: 작업 내용
      description: 진행할 작업에 대해 상세히 설명해주세요.
      placeholder: |
        예) 사용자 로그인 기능 구현, 데이터베이스 스키마 설계 등
    validations:
      required: true

  - type: checkboxes
    id: todo-items
    attributes:
      label: 상세 내용
      description: 완료된 TODO에 체크해주세요.
      options:
        - label: TODO 1
        - label: TODO 2
