version: '3.8'

services:
  spring:
    build:
      context: ..
      dockerfile: .deploy/Dockerfile
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
      - SMS_PROVIDER=${SMS_PROVIDER}
      - SMS_TEMPLATE_AUTH=${SMS_TEMPLATE_AUTH}
      - SMS_LIMIT_AMOUNT=${SMS_LIMIT_AMOUNT}
      - SMS_LIMIT_DURATION_MINUTES=${SMS_LIMIT_DURATION_MINUTES}
      - NCP_SMS_SERVICE_ID=${NCP_SMS_SERVICE_ID}
      - NCP_SMS_API_URL=${NCP_SMS_API_URL}
      - NCP_ACCESS_KEY=${NCP_ACCESS_KEY}
      - NCP_SECRET_KEY=${NCP_SECRET_KEY}
      - NCP_COUNTRY_CODE=${NCP_COUNTRY_CODE}
      - NCP_FROM=${NCP_FROM}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/iroff?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ./build/libs:/app/build/libs
    depends_on:
      - db
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - spring
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=iroff
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-time-zone=+09:00
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - TZ=Asia/Seoul
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge 